server:
  port: 9000
loggin:
  level:
    org:
      springframework:
        security: TRACE
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth}${DB_PARAMS:?preparedThreshold=0}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:userDB}
    password: ${DB_PASSWORD:passwordDB}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 80
      minimum-idle: 1
      idle-timeout: 120000
      initialization-fail-timeout: 5000
      data-source-properties:
        preparedStatementCacheQueries: 0
