server:
  port: 9000
loggin:
  level:
    org:
      springframework:
        security: TRACE
spring:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth}${DB_PARAMS:?preparedThreshold=0}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:userDB}
    password: ${DB_PASSWORD:passwordDB}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 80
      minimum-idle: 1
      idle-timeout: 120000
      initialization-fail-timeout: 5000
      data-source-properties:
        preparedStatementCacheQueries: 0
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google_client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google_client_secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: oauth2-tutorial-client
        provider:
          google:
            user-name-attribute: email