version: '3.8'

services:
  my_postgres:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: userDB
      POSTGRES_PASSWORD: passwordDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-net

volumes:
  postgres_data:

networks:
  auth-net:
    name: auth-net
